input:
  file_name: "parsed/AAA0371-pc.csv"   # Path to the input file
  lines_in_file: 843                    # 5110 - CGM, 843 - AAA
  max_chunk_size: 843                     # Maximum size of input chunk size (useful for large files)
  train_set_percentage: 100                # Percent rate of the train set
input_vector:
  - "minute"
model:
  type: "gru" # "gru" "rnn"
  dir: "pc/AAA0371"
  dirh: "models/minute/AAA0371"
  look_back: 1
  iterations: 5
  metric: "r2"
  round: 0
  transform: 1